import argon2 from "argon2";
import { randomBytes,randomUUID } from "node:crypto";
import { audit } from "./audit.js";
import { config } from "./config.js";
import { one,run } from "./database.js";
import { decryptText,encryptText,sha256 } from "./crypto.js";
import { loadMasterKey } from "./dpapi.js";
import { createTotpSecret,totpUri,verifyTotp } from "./totp.js";

export type VaultRole="vault_admin"|"vault_operator"|"vault_auditor";
type User={id:string;username:string;password_hash:string;mfa_secret_enc:string;role:VaultRole;active:number;failed_attempts:number;locked_until:string|null};
export async function createFirstAdmin(username:string,password:string){if(one<{count:number}>("select count(*) count from vault_users")?.count)throw new Error("O primeiro administrador ja foi criado.");if(password.length<14)throw new Error("Use uma senha com pelo menos 14 caracteres.");const id=randomUUID(),secret=createTotpSecret(),now=new Date().toISOString();const hash=await argon2.hash(password,{type:argon2.argon2id,memoryCost:65536,timeCost:3,parallelism:1});run("insert into vault_users(id,username,password_hash,mfa_secret_enc,role,created_at,updated_at) values(?,?,?,?,?,?,?)",id,username.trim().toLowerCase(),hash,encryptText(secret,loadMasterKey())!,"vault_admin",now,now);audit({userId:id,action:"first_admin_created",result:"success",objectType:"vault_user",objectId:id});return {userId:id,mfaUri:totpUri(username,secret),mfaSecret:secret};}
export async function createVaultUser(username:string,password:string,role:VaultRole){if(!["vault_admin","vault_operator","vault_auditor"].includes(role))throw new Error("ROLE_INVALID");if(password.length<14)throw new Error("Use uma senha com pelo menos 14 caracteres.");if(!one<{count:number}>("select count(*) count from vault_users")?.count)throw new Error("Crie primeiro o administrador inicial.");const id=randomUUID(),secret=createTotpSecret(),now=new Date().toISOString(),hash=await argon2.hash(password,{type:argon2.argon2id,memoryCost:65536,timeCost:3,parallelism:1});run("insert into vault_users(id,username,password_hash,mfa_secret_enc,role,created_at,updated_at) values(?,?,?,?,?,?,?)",id,username.trim().toLowerCase(),hash,encryptText(secret,loadMasterKey())!,role,now,now);audit({action:"vault_user_created_by_local_operator",result:"success",objectType:"vault_user",objectId:id,metadata:{role}});return{userId:id,mfaUri:totpUri(username,secret)};}
export async function login(username:string,password:string,totp:string,address:string){const user=one<User>("select * from vault_users where username=?",username.trim().toLowerCase());const now=Date.now();if(!user||!user.active){audit({action:"login_denied",result:"denied",localAddress:address});throw new Error("Credenciais invalidas.");}if(user.locked_until&&Date.parse(user.locked_until)>now){audit({userId:user.id,action:"login_locked",result:"denied",localAddress:address});throw new Error("Acesso temporariamente bloqueado.");}const passwordOk=await argon2.verify(user.password_hash,password).catch(()=>false);const secret=decryptText(user.mfa_secret_enc,loadMasterKey());if(!passwordOk||!secret||!verifyTotp(secret,totp)){const failures=user.failed_attempts+1;const delay=failures>=5?Math.min(60,2**Math.min(failures-5,6)):0;run("update vault_users set failed_attempts=?,locked_until=?,updated_at=? where id=?",failures,delay?new Date(now+delay*60_000).toISOString():null,new Date().toISOString(),user.id);audit({userId:user.id,action:"login_denied",result:"denied",localAddress:address,metadata:{failedAttempts:failures}});throw new Error("Credenciais ou MFA invalidos.");}run("update vault_users set failed_attempts=0,locked_until=null,updated_at=? where id=?",new Date().toISOString(),user.id);const token=randomBytes(32).toString("base64url"),csrf=randomBytes(24).toString("base64url"),id=randomUUID(),created=new Date(),expires=new Date(created.getTime()+config.sessionMaxMs);run("insert into vault_sessions(id,user_id,token_hash,csrf_hash,created_at,last_activity_at,expires_at,local_address) values(?,?,?,?,?,?,?,?)",id,user.id,sha256(token),sha256(csrf),created.toISOString(),created.toISOString(),expires.toISOString(),address);audit({userId:user.id,action:"login_success",result:"success",localAddress:address});return {token,csrf,user:{id:user.id,username:user.username,role:user.role},expiresAt:expires.toISOString()};}
export function authenticate(token:string|undefined,csrf:string|undefined,mutating:boolean){if(!token)return null;const session=one<{id:string;user_id:string;csrf_hash:string;created_at:string;last_activity_at:string;expires_at:string;revoked_at:string|null;username:string;role:VaultRole;active:number}>("select s.*,u.username,u.role,u.active from vault_sessions s join vault_users u on u.id=s.user_id where s.token_hash=?",sha256(token));const now=Date.now();if(!session||session.revoked_at||!session.active||Date.parse(session.expires_at)<=now||now-Date.parse(session.last_activity_at)>config.sessionIdleMs){if(session&&!session.revoked_at)run("update vault_sessions set revoked_at=? where id=?",new Date().toISOString(),session.id);return null;}if(mutating&&(!csrf||sha256(csrf)!==session.csrf_hash))return null;run("update vault_sessions set last_activity_at=? where id=?",new Date().toISOString(),session.id);return {sessionId:session.id,userId:session.user_id,username:session.username,role:session.role};}
export function rotateCsrf(sessionId:string){const csrf=randomBytes(24).toString("base64url");run("update vault_sessions set csrf_hash=? where id=?",sha256(csrf),sessionId);return csrf;}
export function logout(sessionId:string,userId:string,address:string){run("update vault_sessions set revoked_at=? where id=?",new Date().toISOString(),sessionId);audit({userId,action:"logout",result:"success",localAddress:address});}
