import { createHash } from "node:crypto";
import { existsSync,mkdirSync,readFileSync,readdirSync,unlinkSync,writeFileSync } from "node:fs";
import { basename,join,resolve } from "node:path";
import { audit } from "./audit.js";
import { config } from "./config.js";
import { encryptBytes,decryptBytes,type Envelope } from "./crypto.js";
import { loadMasterKey } from "./dpapi.js";

function pruneBackups(){const entries=readdirSync(config.backupDir).filter(n=>n.endsWith(".vault-backup")).sort().reverse();const kept=new Set<string>();const daily=new Set<string>(),weekly=new Set<string>(),monthly=new Set<string>();for(const name of entries){const stamp=name.match(/mrl-vault-(\d{4})-(\d{2})-(\d{2})/)?.slice(1);if(!stamp)continue;const[y,m,d]=stamp,dt=new Date(`${y}-${m}-${d}T12:00:00Z`),day=`${y}-${m}-${d}`,month=`${y}-${m}`,week=`${dt.getUTCFullYear()}-${Math.floor((Number(dt)-Number(new Date(Date.UTC(dt.getUTCFullYear(),0,1))))/604800000)}`;if(daily.size<7&&!daily.has(day)){daily.add(day);kept.add(name);}if(weekly.size<4&&!weekly.has(week)){weekly.add(week);kept.add(name);}if(monthly.size<12&&!monthly.has(month)){monthly.add(month);kept.add(name);}}for(const name of entries)if(!kept.has(name)){unlinkSync(join(config.backupDir,name));const sum=join(config.backupDir,`${name}.sha256`);if(existsSync(sum))unlinkSync(sum);}}
export function createBackup(){const files=[{name:"vault.db",data:readFileSync(config.databasePath).toString("base64")},...readdirSync(config.attachmentDir).map((name)=>({name:`attachments/${name}`,data:readFileSync(join(config.attachmentDir,name)).toString("base64")}))];const payload=Buffer.from(JSON.stringify({version:1,createdAt:new Date().toISOString(),files}),"utf8");const encrypted=Buffer.from(JSON.stringify(encryptBytes(payload,loadMasterKey())),"utf8");const stamp=new Date().toISOString().replace(/[:.]/g,"-");const path=join(config.backupDir,`mrl-vault-${stamp}.vault-backup`);writeFileSync(path,encrypted,{mode:0o600,flag:"wx"});const checksum=createHash("sha256").update(encrypted).digest("hex");writeFileSync(`${path}.sha256`,`${checksum}  ${basename(path)}\n`,{mode:0o600});pruneBackups();audit({action:"backup_created",result:"success",objectType:"backup",objectId:basename(path),metadata:{sizeBytes:encrypted.length,checksum}});return {path,checksum};}
export function restoreBackup(inputPath:string,targetDir:string){const path=resolve(inputPath),target=resolve(targetDir);if(!existsSync(path))throw new Error("BACKUP_NOT_FOUND");if(existsSync(target)&&readdirSync(target).length)throw new Error("RESTORE_TARGET_NOT_EMPTY");mkdirSync(join(target,"attachments"),{recursive:true,mode:0o700});const envelope=JSON.parse(readFileSync(path,"utf8")) as Envelope;const backup=JSON.parse(decryptBytes(envelope,loadMasterKey()).toString("utf8")) as {version:number;files:Array<{name:string;data:string}>};if(backup.version!==1)throw new Error("BACKUP_VERSION_UNSUPPORTED");for(const file of backup.files){const destination=resolve(target,file.name);if(!destination.startsWith(target))throw new Error("BACKUP_PATH_INVALID");writeFileSync(destination,Buffer.from(file.data,"base64"),{mode:0o600});}audit({action:"backup_restored",result:"success",objectType:"backup",objectId:basename(path),metadata:{targetValidated:true}});return {files:backup.files.length,target};}
