import { randomUUID } from "node:crypto";
import { existsSync,readFileSync,unlinkSync,writeFileSync } from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { audit } from "./audit.js";
import { config } from "./config.js";
import { encryptFilePayload,encryptText,sha256,decryptFilePayload,type Envelope } from "./crypto.js";
import { loadMasterKey } from "./dpapi.js";
import { one,run } from "./database.js";

const officePackage=(bytes:Buffer,folder:"word/"|"xl/")=>bytes.subarray(0,2).toString()==="PK"&&bytes.includes(Buffer.from("[Content_Types].xml"))&&bytes.includes(Buffer.from(folder));
const allowed:Record<string,(b:Buffer)=>boolean>={"application/pdf":b=>b.subarray(0,5).toString()==="%PDF-","image/jpeg":b=>b[0]===0xff&&b[1]===0xd8&&b[2]===0xff,"image/png":b=>b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),"image/webp":b=>b.subarray(0,4).toString()==="RIFF"&&b.subarray(8,12).toString()==="WEBP","text/plain":b=>!b.includes(0),"application/vnd.openxmlformats-officedocument.wordprocessingml.document":b=>officePackage(b,"word/"),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":b=>officePackage(b,"xl/")};
export function validateFile(bytes:Buffer,mime:string){if(bytes.length<=0||bytes.length>config.maxFileBytes)throw new Error("FILE_SIZE_INVALID");const signature=allowed[mime];if(!signature||!signature(bytes))throw new Error("FILE_TYPE_BLOCKED");}
function scan(path:string){const roots=[process.env.ProgramFiles,process.env["ProgramFiles(x86)"],process.env.ProgramData].filter(Boolean) as string[];const executable=roots.map((root)=>join(root,"Windows Defender","MpCmdRun.exe")).find(existsSync);if(!executable)throw new Error("ANTIMALWARE_UNAVAILABLE");const result=spawnSync(executable,["-Scan","-ScanType","3","-File",path,"-DisableRemediation"],{windowsHide:true,encoding:"utf8",timeout:120_000});if(result.status!==0)throw new Error("FILE_QUARANTINED");}
export function storeDocument(clientId:string,meta:Record<string,unknown>,bytes:Buffer,userId:string,address:string){const mime=String(meta.mimeType||"");validateFile(bytes,mime);const id=randomUUID(),physical=randomUUID(),quarantine=join(config.quarantineDir,physical);writeFileSync(quarantine,bytes,{mode:0o600,flag:"wx"});try{scan(quarantine);const master=loadMasterKey(),encrypted=encryptFilePayload(bytes,master),target=join(config.attachmentDir,physical);writeFileSync(target,JSON.stringify(encrypted.payload),{mode:0o600,flag:"wx"});const now=new Date().toISOString();run("insert into vault_documents(id,client_id,title_enc,original_name_enc,description_enc,document_type,document_on,expires_on,country_code,document_number_enc,tags_enc,physical_name,size_bytes,mime_type,sha256,file_key_enc,status,created_by,created_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,clientId,encryptText(String(meta.title||"Documento"),master)!,encryptText(String(meta.originalName||"arquivo"),master)!,encryptText(typeof meta.description==="string"?meta.description:null,master),String(meta.documentType||"Outro"),typeof meta.documentOn==="string"?meta.documentOn:null,typeof meta.expiresOn==="string"?meta.expiresOn:null,typeof meta.countryCode==="string"?meta.countryCode:null,encryptText(typeof meta.documentNumber==="string"?meta.documentNumber:null,master),encryptText(Array.isArray(meta.tags)?JSON.stringify(meta.tags):null,master),physical,bytes.length,mime,sha256(bytes),JSON.stringify(encrypted.wrappedKey),"active",userId,now);audit({userId,action:"document_uploaded",clientId,objectType:"document",objectId:id,result:"success",localAddress:address,metadata:{mimeType:mime,sizeBytes:bytes.length}});return {id};}finally{if(existsSync(quarantine))unlinkSync(quarantine);}}
export function readDocument(clientId:string,id:string,userId:string,address:string){const row=one<{physical_name:string;file_key_enc:string;mime_type:string}>("select physical_name,file_key_enc,mime_type from vault_documents where id=? and client_id=? and deleted_at is null",id,clientId);if(!row)throw new Error("NOT_FOUND");const payload=JSON.parse(readFileSync(join(config.attachmentDir,row.physical_name),"utf8")) as Envelope;const bytes=decryptFilePayload(payload,JSON.parse(row.file_key_enc) as Envelope,loadMasterKey());audit({userId,action:"document_viewed_or_downloaded",clientId,objectType:"document",objectId:id,result:"success",localAddress:address});return {bytes,mimeType:row.mime_type};}
export function deleteDocument(clientId:string,id:string,userId:string,address:string){const result=run("update vault_documents set deleted_at=?,status='deleted' where id=? and client_id=? and deleted_at is null",new Date().toISOString(),id,clientId);if(!result.changes)throw new Error("NOT_FOUND");audit({userId,action:"document_soft_deleted",clientId,objectType:"document",objectId:id,result:"success",localAddress:address});}
