import { randomUUID } from "node:crypto";
import { audit } from "./audit.js";
import { all,one,run,transaction } from "./database.js";
import { decryptText,encryptText } from "./crypto.js";
import { loadMasterKey } from "./dpapi.js";
import type { VaultRole } from "./auth.js";

export type VaultSyncStatus="synced"|"pending"|"failed"|"archived";
export type ProvisioningEvent={eventId:string;clientId:string;displayName:string;contractStartDate:string|null;contractEndDate:string|null;eventType:string;occurredAt?:string};
const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const isClientId=(value:string)=>uuidPattern.test(value);

const defaults=[
  ["LATAM Pass","https://www.latamairlines.com/br/pt/latam-pass","latam-pass"],["Livelo","https://www.livelo.com.br/","livelo"],
  ["Azul Fidelidade","https://www.voeazul.com.br/br/pt/programa-fidelidade","azul"],["Smiles","https://www.smiles.com.br/","smiles"],["Esfera","https://www.esfera.com.vc/","esfera"],
] as const;
export function safeServiceUrl(value:string){const url=new URL(value);if(!["https:","http:"].includes(url.protocol))throw new Error("URL_BLOCKED");if(url.username||url.password)throw new Error("URL_BLOCKED");return url.toString();}
export function nextBirthday(birthDate:string,today=new Date()){const [year,month,day]=birthDate.split("-").map(Number);if(!year||!month||!day)throw new Error("INVALID_BIRTH_DATE");const y=today.getFullYear();const build=(targetYear:number)=>month===2&&day===29&&!isLeap(targetYear)?new Date(targetYear,1,28):new Date(targetYear,month-1,day);let result=build(y);const start=new Date(today.getFullYear(),today.getMonth(),today.getDate());if(result<start)result=build(y+1);return [result.getFullYear(),String(result.getMonth()+1).padStart(2,"0"),String(result.getDate()).padStart(2,"0")].join("-");}
const isLeap=(year:number)=>year%4===0&&(year%100!==0||year%400===0);
export function recordSyncEvent(event:ProvisioningEvent,status:VaultSyncStatus="pending",lastError:string|null=null){
  if(!isClientId(event.clientId))throw new Error("INVALID_CLIENT_ID");
  const now=new Date().toISOString();
  run(`insert into vault_client_sync_index(client_id,display_name,contract_start_date,contract_end_date,event_type,sync_status,last_error,occurred_at,updated_at)
    values(?,?,?,?,?,?,?,?,?) on conflict(client_id) do update set display_name=excluded.display_name,contract_start_date=excluded.contract_start_date,
    contract_end_date=excluded.contract_end_date,event_type=excluded.event_type,sync_status=excluded.sync_status,last_error=excluded.last_error,
    occurred_at=excluded.occurred_at,updated_at=excluded.updated_at`,event.clientId,event.displayName,event.contractStartDate,event.contractEndDate,event.eventType,status,lastError,event.occurredAt??now,now);
}
export function markClientSyncPending(clientId:string){if(!isClientId(clientId))throw new Error("INVALID_CLIENT_ID");const result=run("update vault_client_sync_index set sync_status='pending',last_error=null,updated_at=? where client_id=?",new Date().toISOString(),clientId);if(!result.changes)throw new Error("NOT_FOUND");}
export function markClientSyncFailed(event:ProvisioningEvent){recordSyncEvent(event,"failed","Nao foi possivel gravar este cliente no cofre local.");}
export function provisionClient(event:ProvisioningEvent,actor="sync-agent"){
  if(one("select event_id from processed_outbox_events where event_id=?",event.eventId))return {idempotentReplay:true};
  transaction(()=>{const now=new Date().toISOString();const archived=event.eventType==="client_vault_archive";run(`insert into vault_clients(client_id,display_name,status,contract_start_date,contract_end_date,sync_status,created_at,updated_at,last_admin_user_id) values(?,?,?,?,?,'synced',?,?,?) on conflict(client_id) do update set display_name=excluded.display_name,status=excluded.status,contract_start_date=excluded.contract_start_date,contract_end_date=excluded.contract_end_date,sync_status='synced',updated_at=excluded.updated_at,last_admin_user_id=excluded.last_admin_user_id`,event.clientId,event.displayName,archived?"archived":"active",event.contractStartDate,event.contractEndDate,now,now,actor);for(const [name,url,icon] of defaults){run("insert into vault_credentials(id,client_id,service_name,service_url,icon_key,status,changed_at,created_by,updated_by,created_at,updated_at) select ?,?,?,?,?,?,?,?,?,?,? where not exists(select 1 from vault_credentials where client_id=? and service_name=?)",randomUUID(),event.clientId,name,url,icon,"inactive",now,actor,actor,now,now,event.clientId,name);}recordSyncEvent(event,archived?"archived":"synced");run("insert into processed_outbox_events(event_id,processed_at) values(?,?)",event.eventId,now);audit({userId:actor,action:event.eventType,clientId:event.clientId,objectType:"vault_client",objectId:event.clientId,result:"success"});});return {idempotentReplay:false};
}
export function listClients(role:VaultRole){
  const local=all<Record<string,unknown>>("select client_id,display_name,status,contract_start_date,contract_end_date,sync_status,created_at,updated_at from vault_clients order by display_name collate nocase");
  const index=all<Record<string,unknown>>("select * from vault_client_sync_index order by display_name collate nocase");
  const merged=new Map<string,Record<string,unknown>>();
  for(const item of index)merged.set(String(item.client_id),{clientId:item.client_id,displayName:item.display_name,status:item.sync_status==="archived"?"archived":"active",contractStartDate:item.contract_start_date,contractEndDate:item.contract_end_date,syncStatus:item.sync_status,lastError:item.last_error,updatedAt:item.updated_at,localDataAvailable:false});
  for(const item of local)merged.set(String(item.client_id),{clientId:item.client_id,displayName:item.display_name,status:item.status,contractStartDate:item.contract_start_date,contractEndDate:item.contract_end_date,syncStatus:item.status==="archived"?"archived":item.sync_status,lastError:null,updatedAt:item.updated_at,localDataAvailable:role!=="vault_auditor"});
  return {items:[...merged.values()].sort((a,b)=>String(a.displayName).localeCompare(String(b.displayName),"pt-BR")),total:merged.size};
}
const emptyPersonal={cpf:null,rg:null,birthDate:null,nextBirthday:null,email:null,phone:null,address:null,maritalStatus:null,passport:null,privateNotes:null};
export function getClient(clientId:string,role:VaultRole){if(!isClientId(clientId))throw new Error("INVALID_CLIENT_ID");if(role==="vault_auditor")throw new Error("FORBIDDEN");const client=one<Record<string,unknown>>("select * from vault_clients where client_id=?",clientId);if(!client){const pending=one<Record<string,unknown>>("select * from vault_client_sync_index where client_id=?",clientId);if(!pending)throw new Error("NOT_FOUND");return {clientId,displayName:pending.display_name,status:pending.sync_status==="archived"?"archived":"active",contractStartDate:pending.contract_start_date,contractEndDate:pending.contract_end_date,syncStatus:pending.sync_status,lastError:pending.last_error,createdAt:pending.occurred_at,updatedAt:pending.updated_at,lastAdminUserId:null,localDataAvailable:false,personal:emptyPersonal,credentials:[],documents:[]};}const key=loadMasterKey();const birth=decryptText(client.birth_date_enc as string|null,key);return {clientId,displayName:client.display_name,status:client.status,contractStartDate:client.contract_start_date,contractEndDate:client.contract_end_date,syncStatus:client.status==="archived"?"archived":client.sync_status,lastError:null,createdAt:client.created_at,updatedAt:client.updated_at,lastAdminUserId:client.last_admin_user_id,localDataAvailable:true,personal:{cpf:decryptText(client.cpf_enc as string|null,key),rg:decryptText(client.rg_enc as string|null,key),birthDate:birth,nextBirthday:birth?nextBirthday(birth):null,email:decryptText(client.email_enc as string|null,key),phone:decryptText(client.phone_enc as string|null,key),address:decryptText(client.address_enc as string|null,key),maritalStatus:decryptText(client.marital_status_enc as string|null,key),passport:decryptText(client.passport_enc as string|null,key),privateNotes:decryptText(client.private_notes_enc as string|null,key)},credentials:listCredentials(clientId),documents:listDocuments(clientId)};}
export function updatePersonal(clientId:string,input:Record<string,unknown>,userId:string){const value=(field:string,max:number)=>typeof input[field]==="string"?String(input[field]).trim().slice(0,max):null;const cpf=value("cpf",14),phone=value("phone",30),email=value("email",254),birth=value("birthDate",10);if(cpf&&cpf.replace(/\D/g,"").length!==11)throw new Error("INVALID_CPF");if(phone&&!/^\+?[\d ()-]{8,30}$/.test(phone))throw new Error("INVALID_PHONE");if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("INVALID_EMAIL");if(birth&&!/^\d{4}-\d{2}-\d{2}$/.test(birth))throw new Error("INVALID_BIRTH_DATE");const normalized={cpf,rg:value("rg",30),birthDate:birth,email,phone,address:value("address",500),maritalStatus:value("maritalStatus",80),passport:value("passport",80),privateNotes:value("privateNotes",5000)};const key=loadMasterKey();const allowed=["cpf","rg","birthDate","email","phone","address","maritalStatus","passport","privateNotes"] as const;const values=allowed.map((field)=>encryptText(normalized[field],key));const result=run("update vault_clients set cpf_enc=?,rg_enc=?,birth_date_enc=?,email_enc=?,phone_enc=?,address_enc=?,marital_status_enc=?,passport_enc=?,private_notes_enc=?,updated_at=?,last_admin_user_id=? where client_id=?",...values,new Date().toISOString(),userId,clientId);if(!result.changes)throw new Error("CLIENT_NOT_SYNCED");audit({userId,action:"personal_data_updated",clientId,objectType:"vault_client",objectId:clientId,result:"success",metadata:{fields:allowed.filter((field)=>field in input)}});return getClient(clientId,"vault_operator");}
export function listCredentials(clientId:string){return all<Record<string,unknown>>("select id,service_name,service_url,icon_key,status,changed_at,review_on,updated_at from vault_credentials where client_id=? and deleted_at is null order by service_name",clientId).map((row)=>({id:row.id,serviceName:row.service_name,serviceUrl:row.service_url,iconKey:row.icon_key,status:row.status,changedAt:row.changed_at,reviewOn:row.review_on,updatedAt:row.updated_at}));}
export function saveCredential(clientId:string,input:Record<string,unknown>,userId:string){const key=loadMasterKey(),id=typeof input.id==="string"?input.id:randomUUID(),now=new Date().toISOString(),url=safeServiceUrl(String(input.serviceUrl||""));run(`insert into vault_credentials(id,client_id,service_name,service_url,icon_key,login_enc,password_enc,notes_enc,status,changed_at,review_on,created_by,updated_by,created_at,updated_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(id) do update set service_name=excluded.service_name,service_url=excluded.service_url,icon_key=excluded.icon_key,login_enc=coalesce(excluded.login_enc,vault_credentials.login_enc),password_enc=coalesce(excluded.password_enc,vault_credentials.password_enc),notes_enc=excluded.notes_enc,status=excluded.status,changed_at=excluded.changed_at,review_on=excluded.review_on,updated_by=excluded.updated_by,updated_at=excluded.updated_at`,id,clientId,String(input.serviceName||"").trim(),url,typeof input.iconKey==="string"?input.iconKey:null,encryptText(typeof input.login==="string"?input.login:null,key),encryptText(typeof input.password==="string"?input.password:null,key),encryptText(typeof input.notes==="string"?input.notes:null,key),String(input.status||"active"),now,typeof input.reviewOn==="string"?input.reviewOn:null,userId,userId,now,now);audit({userId,action:"credential_saved",clientId,objectType:"credential",objectId:id,result:"success"});return {id};}
export function revealCredential(clientId:string,credentialId:string,field:"login"|"password",userId:string,address:string,purpose:"reveal"|"copy"="reveal"){const row=one<{login_enc:string|null;password_enc:string|null}>("select login_enc,password_enc from vault_credentials where id=? and client_id=? and deleted_at is null",credentialId,clientId);if(!row)throw new Error("NOT_FOUND");const value=decryptText(field==="login"?row.login_enc:row.password_enc,loadMasterKey());audit({userId,action:`${purpose}_${field}`,clientId,objectType:"credential",objectId:credentialId,result:"success",localAddress:address});return {value};}
export function listDocuments(clientId:string){const key=loadMasterKey();return all<Record<string,unknown>>("select id,title_enc,original_name_enc,document_type,document_on,expires_on,country_code,size_bytes,mime_type,sha256,created_at from vault_documents where client_id=? and deleted_at is null order by created_at desc",clientId).map((row)=>({id:row.id,title:decryptText(row.title_enc as string,key),originalName:decryptText(row.original_name_enc as string,key),documentType:row.document_type,documentOn:row.document_on,expiresOn:row.expires_on,countryCode:row.country_code,sizeBytes:row.size_bytes,mimeType:row.mime_type,sha256:row.sha256,createdAt:row.created_at}));}
