import { randomUUID } from "node:crypto";
import { audit } from "./audit.js";
import { all,one,run,transaction } from "./database.js";
import { decryptText,encryptText } from "./crypto.js";
import { loadMasterKey } from "./dpapi.js";
import type { VaultRole } from "./auth.js";

const defaults=[
  ["LATAM Pass","https://www.latamairlines.com/br/pt/latam-pass","latam-pass"],["Livelo","https://www.livelo.com.br/","livelo"],
  ["Azul Fidelidade","https://www.voeazul.com.br/br/pt/programa-fidelidade","azul"],["Smiles","https://www.smiles.com.br/","smiles"],["Esfera","https://www.esfera.com.vc/","esfera"],
] as const;
export function safeServiceUrl(value:string){const url=new URL(value);if(!["https:","http:"].includes(url.protocol))throw new Error("URL_BLOCKED");if(url.username||url.password)throw new Error("URL_BLOCKED");return url.toString();}
export function nextBirthday(birthDate:string,today=new Date()){const [year,month,day]=birthDate.split("-").map(Number);if(!year||!month||!day)throw new Error("INVALID_BIRTH_DATE");const y=today.getFullYear();const build=(targetYear:number)=>month===2&&day===29&&!isLeap(targetYear)?new Date(targetYear,1,28):new Date(targetYear,month-1,day);let result=build(y);const start=new Date(today.getFullYear(),today.getMonth(),today.getDate());if(result<start)result=build(y+1);return [result.getFullYear(),String(result.getMonth()+1).padStart(2,"0"),String(result.getDate()).padStart(2,"0")].join("-");}
const isLeap=(year:number)=>year%4===0&&(year%100!==0||year%400===0);
export function provisionClient(event:{eventId:string;clientId:string;displayName:string;contractStartDate:string|null;contractEndDate:string|null;eventType:string},actor="sync-agent"){
  if(one("select event_id from processed_outbox_events where event_id=?",event.eventId))return {idempotentReplay:true};
  transaction(()=>{const now=new Date().toISOString();const archived=event.eventType==="client_vault_archive";run(`insert into vault_clients(client_id,display_name,status,contract_start_date,contract_end_date,sync_status,created_at,updated_at,last_admin_user_id) values(?,?,?,?,?,'synced',?,?,?) on conflict(client_id) do update set display_name=excluded.display_name,status=excluded.status,contract_start_date=excluded.contract_start_date,contract_end_date=excluded.contract_end_date,sync_status='synced',updated_at=excluded.updated_at,last_admin_user_id=excluded.last_admin_user_id`,event.clientId,event.displayName,archived?"archived":"active",event.contractStartDate,event.contractEndDate,now,now,actor);for(const [name,url,icon] of defaults){run("insert into vault_credentials(id,client_id,service_name,service_url,icon_key,status,changed_at,created_by,updated_by,created_at,updated_at) select ?,?,?,?,?,?,?,?,?,?,? where not exists(select 1 from vault_credentials where client_id=? and service_name=?)",randomUUID(),event.clientId,name,url,icon,"inactive",now,actor,actor,now,now,event.clientId,name);}run("insert into processed_outbox_events(event_id,processed_at) values(?,?)",event.eventId,now);audit({userId:actor,action:event.eventType,clientId:event.clientId,objectType:"vault_client",objectId:event.clientId,result:"success"});});return {idempotentReplay:false};
}
export function getClient(clientId:string,role:VaultRole){if(role==="vault_auditor")throw new Error("FORBIDDEN");const client=one<Record<string,unknown>>("select * from vault_clients where client_id=?",clientId);if(!client)throw new Error("CLIENT_NOT_SYNCED");const key=loadMasterKey();const birth=decryptText(client.birth_date_enc as string|null,key);return {clientId,displayName:client.display_name,status:client.status,contractStartDate:client.contract_start_date,contractEndDate:client.contract_end_date,syncStatus:client.sync_status,createdAt:client.created_at,updatedAt:client.updated_at,lastAdminUserId:client.last_admin_user_id,personal:{cpf:decryptText(client.cpf_enc as string|null,key),rg:decryptText(client.rg_enc as string|null,key),birthDate:birth,nextBirthday:birth?nextBirthday(birth):null,email:decryptText(client.email_enc as string|null,key),phone:decryptText(client.phone_enc as string|null,key),address:decryptText(client.address_enc as string|null,key),maritalStatus:decryptText(client.marital_status_enc as string|null,key),passportNumber:decryptText(client.passport_number_enc as string|null,key),passportCountry:decryptText(client.passport_country_enc as string|null,key),passportExpiry:decryptText(client.passport_expiry_enc as string|null,key),privateNotes:decryptText(client.private_notes_enc as string|null,key)},credentials:listCredentials(clientId),documents:listDocuments(clientId)};}
export function updatePersonal(clientId:string,input:Record<string,unknown>,userId:string){const value=(field:string,max:number)=>typeof input[field]==="string"?String(input[field]).trim().slice(0,max):null;const cpf=value("cpf",14),phone=value("phone",30),email=value("email",254),birth=value("birthDate",10),passportExpiry=value("passportExpiry",10);if(cpf&&cpf.replace(/\D/g,"").length!==11)throw new Error("INVALID_CPF");if(phone&&!/^\+?[\d ()-]{8,30}$/.test(phone))throw new Error("INVALID_PHONE");if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("INVALID_EMAIL");if(birth&&!/^\d{4}-\d{2}-\d{2}$/.test(birth))throw new Error("INVALID_BIRTH_DATE");if(passportExpiry&&!/^\d{4}-\d{2}-\d{2}$/.test(passportExpiry))throw new Error("INVALID_PASSPORT_EXPIRY");const normalized={cpf,rg:value("rg",30),birthDate:birth,email,phone,address:value("address",500),maritalStatus:value("maritalStatus",60),passportNumber:value("passportNumber",30),passportCountry:value("passportCountry",3),passportExpiry,privateNotes:value("privateNotes",5000)};const key=loadMasterKey();const allowed=["cpf","rg","birthDate","email","phone","address","maritalStatus","passportNumber","passportCountry","passportExpiry","privateNotes"] as const;const values=allowed.map((field)=>encryptText(normalized[field],key));const result=run("update vault_clients set cpf_enc=?,rg_enc=?,birth_date_enc=?,email_enc=?,phone_enc=?,address_enc=?,marital_status_enc=?,passport_number_enc=?,passport_country_enc=?,passport_expiry_enc=?,private_notes_enc=?,updated_at=?,last_admin_user_id=? where client_id=?",...values,new Date().toISOString(),userId,clientId);if(!result.changes)throw new Error("CLIENT_NOT_SYNCED");audit({userId,action:"personal_data_updated",clientId,objectType:"vault_client",objectId:clientId,result:"success",metadata:{fields:allowed.filter((field)=>field in input)}});return getClient(clientId,"vault_operator");}
export function listCredentials(clientId:string){return all<Record<string,unknown>>("select id,service_name,service_url,icon_key,status,changed_at,review_on,updated_at from vault_credentials where client_id=? and deleted_at is null order by service_name",clientId).map((row)=>({id:row.id,serviceName:row.service_name,serviceUrl:row.service_url,iconKey:row.icon_key,status:row.status,changedAt:row.changed_at,reviewOn:row.review_on,updatedAt:row.updated_at}));}
export function saveCredential(clientId:string,input:Record<string,unknown>,userId:string){const key=loadMasterKey(),id=typeof input.id==="string"?input.id:randomUUID(),now=new Date().toISOString(),url=safeServiceUrl(String(input.serviceUrl||""));run(`insert into vault_credentials(id,client_id,service_name,service_url,icon_key,login_enc,password_enc,notes_enc,status,changed_at,review_on,created_by,updated_by,created_at,updated_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(id) do update set service_name=excluded.service_name,service_url=excluded.service_url,icon_key=excluded.icon_key,login_enc=coalesce(excluded.login_enc,vault_credentials.login_enc),password_enc=coalesce(excluded.password_enc,vault_credentials.password_enc),notes_enc=excluded.notes_enc,status=excluded.status,changed_at=excluded.changed_at,review_on=excluded.review_on,updated_by=excluded.updated_by,updated_at=excluded.updated_at`,id,clientId,String(input.serviceName||"").trim(),url,typeof input.iconKey==="string"?input.iconKey:null,encryptText(typeof input.login==="string"?input.login:null,key),encryptText(typeof input.password==="string"?input.password:null,key),encryptText(typeof input.notes==="string"?input.notes:null,key),String(input.status||"active"),now,typeof input.reviewOn==="string"?input.reviewOn:null,userId,userId,now,now);audit({userId,action:"credential_saved",clientId,objectType:"credential",objectId:id,result:"success"});return {id};}
export function revealCredential(clientId:string,credentialId:string,field:"login"|"password",userId:string,address:string){const row=one<{login_enc:string|null;password_enc:string|null}>("select login_enc,password_enc from vault_credentials where id=? and client_id=? and deleted_at is null",credentialId,clientId);if(!row)throw new Error("NOT_FOUND");const value=decryptText(field==="login"?row.login_enc:row.password_enc,loadMasterKey());audit({userId,action:field==="login"?"copy_login":"reveal_or_copy_password",clientId,objectType:"credential",objectId:credentialId,result:"success",localAddress:address});return {value};}
export function listDocuments(clientId:string){const key=loadMasterKey();return all<Record<string,unknown>>("select id,title_enc,original_name_enc,document_type,document_on,expires_on,country_code,size_bytes,mime_type,sha256,created_at from vault_documents where client_id=? and deleted_at is null order by created_at desc",clientId).map((row)=>({id:row.id,title:decryptText(row.title_enc as string,key),originalName:decryptText(row.original_name_enc as string,key),documentType:row.document_type,documentOn:row.document_on,expiresOn:row.expires_on,countryCode:row.country_code,sizeBytes:row.size_bytes,mimeType:row.mime_type,sha256:row.sha256,createdAt:row.created_at}));}
