import { randomUUID } from "node:crypto";
import { audit } from "./audit.js";
import { all,one,run,transaction } from "./database.js";
import { decryptText,encryptText } from "./crypto.js";
import { loadMasterKey } from "./dpapi.js";
import type { VaultRole } from "./auth.js";

export type VaultSyncStatus="synced"|"pending"|"failed"|"archived";
export type ProvisioningEvent={eventId:string;clientId:string;displayName:string;contractStartDate:string|null;contractEndDate:string|null;eventType:string;occurredAt?:string};
const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export const isClientId=(value:string)=>uuidPattern.test(value);

const defaults=[
  ["LATAM Pass","https://www.latamairlines.com/br/pt/latam-pass","latam-pass"],
  ["Livelo","https://www.livelo.com.br/","livelo"],
  ["Azul Fidelidade","https://www.voeazul.com.br/br/pt/programa-fidelidade","azul"],
  ["Smiles","https://www.smiles.com.br/","smiles"],
  ["Esfera","https://www.esfera.com.vc/","esfera"],
] as const;
const inputText=(input:Record<string,unknown>,field:string,max:number)=>typeof input[field]==="string"?String(input[field]).trim().slice(0,max):null;
const isoDate=(value:string|null,code="INVALID_DATE")=>{if(value&&!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error(code);return value;};
const numberDay=(value:unknown)=>value===""||value==null?null:Number(value);
const assertDay=(value:number|null)=>{if(value!==null&&(!Number.isInteger(value)||value<1||value>31))throw new Error("INVALID_CARD_DAY");};
const ensureScopedId=(table:string,id:string|undefined,clientId:string)=>{if(!id)return randomUUID();if(!uuidPattern.test(id))throw new Error("INVALID_ID");const row=one<{client_id:string}>(`select client_id from ${table} where id=?`,id);if(row&&row.client_id!==clientId)throw new Error("FORBIDDEN");return id;};

export function safeServiceUrl(value:string){const url=new URL(value);if(!["https:","http:"].includes(url.protocol)||url.username||url.password)throw new Error("URL_BLOCKED");return url.toString();}
export function nextBirthday(birthDate:string,today=new Date()){const [year,month,day]=birthDate.split("-").map(Number);if(!year||!month||!day)throw new Error("INVALID_BIRTH_DATE");const current=today.getFullYear();const build=(target:number)=>month===2&&day===29&&!isLeap(target)?new Date(target,1,28):new Date(target,month-1,day);let result=build(current);const start=new Date(today.getFullYear(),today.getMonth(),today.getDate());if(result<start)result=build(current+1);return [result.getFullYear(),String(result.getMonth()+1).padStart(2,"0"),String(result.getDate()).padStart(2,"0")].join("-");}
export function ageOn(birthDate:string,today=new Date()){const [year,month,day]=birthDate.split("-").map(Number);let age=today.getFullYear()-year;if(today.getMonth()+1<month||(today.getMonth()+1===month&&today.getDate()<day))age--;return Math.max(age,0);}
const isLeap=(year:number)=>year%4===0&&(year%100!==0||year%400===0);

export function recordSyncEvent(event:ProvisioningEvent,status:VaultSyncStatus="pending",lastError:string|null=null){if(!isClientId(event.clientId))throw new Error("INVALID_CLIENT_ID");const now=new Date().toISOString();run(`insert into vault_client_sync_index(client_id,display_name,contract_start_date,contract_end_date,event_type,sync_status,last_error,occurred_at,updated_at) values(?,?,?,?,?,?,?,?,?) on conflict(client_id) do update set display_name=excluded.display_name,contract_start_date=excluded.contract_start_date,contract_end_date=excluded.contract_end_date,event_type=excluded.event_type,sync_status=excluded.sync_status,last_error=excluded.last_error,occurred_at=excluded.occurred_at,updated_at=excluded.updated_at`,event.clientId,event.displayName,event.contractStartDate,event.contractEndDate,event.eventType,status,lastError,event.occurredAt??now,now);}
export function provisionClient(event:ProvisioningEvent,actor="sync-agent"){if(!isClientId(event.clientId))throw new Error("INVALID_CLIENT_ID");if(one("select event_id from processed_outbox_events where event_id=?",event.eventId))return {idempotentReplay:true};transaction(()=>{const now=new Date().toISOString(),archived=event.eventType==="client_vault_archive";run(`insert into vault_clients(client_id,display_name,status,contract_start_date,contract_end_date,sync_status,created_at,updated_at,last_admin_user_id) values(?,?,?,?,?,'synced',?,?,?) on conflict(client_id) do update set display_name=excluded.display_name,status=excluded.status,contract_start_date=excluded.contract_start_date,contract_end_date=excluded.contract_end_date,sync_status='synced',updated_at=excluded.updated_at,last_admin_user_id=excluded.last_admin_user_id`,event.clientId,event.displayName,archived?"archived":"active",event.contractStartDate,event.contractEndDate,now,now,actor);for(const [name,url,icon] of defaults)run("insert into vault_credentials(id,client_id,service_name,service_url,icon_key,status,changed_at,created_by,updated_by,created_at,updated_at) select ?,?,?,?,?,?,?,?,?,?,? where not exists(select 1 from vault_credentials where client_id=? and service_name=?)",randomUUID(),event.clientId,name,url,icon,"inactive",now,actor,actor,now,now,event.clientId,name);recordSyncEvent(event,archived?"archived":"synced");run("insert into processed_outbox_events(event_id,processed_at) values(?,?)",event.eventId,now);audit({userId:actor,action:event.eventType,clientId:event.clientId,objectType:"vault_client",objectId:event.clientId,result:"success"});});return {idempotentReplay:false};}
export function markSyncFailed(event:ProvisioningEvent){recordSyncEvent(event,"failed","Nao foi possivel gravar este cadastro no cofre local.");}
export function listClients(role:VaultRole){const local=all<Record<string,unknown>>("select client_id,display_name,status,contract_start_date,contract_end_date,sync_status,updated_at from vault_clients"),index=all<Record<string,unknown>>("select * from vault_client_sync_index"),merged=new Map<string,Record<string,unknown>>();for(const item of index)merged.set(String(item.client_id),{clientId:item.client_id,displayName:item.display_name,status:item.sync_status==="archived"?"archived":"active",contractStartDate:item.contract_start_date,contractEndDate:item.contract_end_date,syncStatus:item.sync_status,lastError:item.last_error,updatedAt:item.updated_at,localDataAvailable:false});for(const item of local)merged.set(String(item.client_id),{clientId:item.client_id,displayName:item.display_name,status:item.status,contractStartDate:item.contract_start_date,contractEndDate:item.contract_end_date,syncStatus:item.status==="archived"?"archived":item.sync_status,lastError:null,updatedAt:item.updated_at,localDataAvailable:role!=="vault_auditor"});return {items:[...merged.values()].sort((a,b)=>String(a.displayName).localeCompare(String(b.displayName),"pt-BR")),total:merged.size};}

const emptyPersonal={cpf:null,rg:null,rgIssuer:null,birthDate:null,age:null,nextBirthday:null,email:null,phone:null,whatsapp:null,address:null,maritalStatus:null,nationality:null,privateNotes:null};
export function getClient(clientId:string,role:VaultRole){if(!isClientId(clientId))throw new Error("INVALID_CLIENT_ID");if(role==="vault_auditor")throw new Error("FORBIDDEN");const client=one<Record<string,unknown>>("select * from vault_clients where client_id=?",clientId);if(!client){const pending=one<Record<string,unknown>>("select * from vault_client_sync_index where client_id=?",clientId);if(!pending)throw new Error("NOT_FOUND");return {clientId,displayName:pending.display_name,status:pending.sync_status==="archived"?"archived":"active",contractStartDate:pending.contract_start_date,contractEndDate:pending.contract_end_date,syncStatus:pending.sync_status,lastError:pending.last_error,createdAt:pending.occurred_at,updatedAt:pending.updated_at,lastAdminUserId:null,localDataAvailable:false,personal:emptyPersonal,credentials:[],documents:[],cards:[],passports:[],visas:[]};}const key=loadMasterKey(),birth=decryptText(client.birth_date_enc as string|null,key);return {clientId,displayName:client.display_name,status:client.status,contractStartDate:client.contract_start_date,contractEndDate:client.contract_end_date,syncStatus:client.status==="archived"?"archived":client.sync_status,lastError:null,createdAt:client.created_at,updatedAt:client.updated_at,lastAdminUserId:client.last_admin_user_id,localDataAvailable:true,personal:{cpf:decryptText(client.cpf_enc as string|null,key),rg:decryptText(client.rg_enc as string|null,key),rgIssuer:decryptText(client.rg_issuer_enc as string|null,key),birthDate:birth,age:birth?ageOn(birth):null,nextBirthday:birth?nextBirthday(birth):null,email:decryptText(client.email_enc as string|null,key),phone:decryptText(client.phone_enc as string|null,key),whatsapp:decryptText(client.whatsapp_enc as string|null,key),address:decryptText(client.address_enc as string|null,key),maritalStatus:decryptText(client.marital_status_enc as string|null,key),nationality:decryptText(client.nationality_enc as string|null,key),privateNotes:decryptText(client.private_notes_enc as string|null,key)},credentials:listCredentials(clientId),documents:listDocuments(clientId),cards:listCards(clientId),passports:listPassports(clientId),visas:listVisas(clientId)};}
export function updatePersonal(clientId:string,input:Record<string,unknown>,userId:string){const cpf=inputText(input,"cpf",14),phone=inputText(input,"phone",30),whatsapp=inputText(input,"whatsapp",30),email=inputText(input,"email",254),birth=isoDate(inputText(input,"birthDate",10),"INVALID_BIRTH_DATE");if(cpf&&cpf.replace(/\D/g,"").length!==11)throw new Error("INVALID_CPF");for(const value of[phone,whatsapp])if(value&&!/^\+?[\d ()-]{8,30}$/.test(value))throw new Error("INVALID_PHONE");if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error("INVALID_EMAIL");const normalized={cpf,rg:inputText(input,"rg",30),rgIssuer:inputText(input,"rgIssuer",60),birthDate:birth,email,phone,whatsapp,address:inputText(input,"address",700),maritalStatus:inputText(input,"maritalStatus",60),nationality:inputText(input,"nationality",80),privateNotes:inputText(input,"privateNotes",5000)},key=loadMasterKey(),allowed=["cpf","rg","rgIssuer","birthDate","email","phone","whatsapp","address","maritalStatus","nationality","privateNotes"] as const,values=allowed.map(field=>encryptText(normalized[field],key)),result=run("update vault_clients set cpf_enc=?,rg_enc=?,rg_issuer_enc=?,birth_date_enc=?,email_enc=?,phone_enc=?,whatsapp_enc=?,address_enc=?,marital_status_enc=?,nationality_enc=?,private_notes_enc=?,updated_at=?,last_admin_user_id=? where client_id=?",...values,new Date().toISOString(),userId,clientId);if(!result.changes)throw new Error("CLIENT_NOT_SYNCED");audit({userId,action:"personal_data_updated",clientId,objectType:"vault_client",objectId:clientId,result:"success",metadata:{fields:allowed.filter(field=>field in input)}});return getClient(clientId,"vault_operator");}

export function listCredentials(clientId:string){const key=loadMasterKey();return all<Record<string,unknown>>("select id,service_name,service_url,icon_key,notes_enc,status,changed_at,review_on,created_at,updated_at from vault_credentials where client_id=? and deleted_at is null order by service_name",clientId).map(row=>({id:row.id,serviceName:row.service_name,serviceUrl:row.service_url,iconKey:row.icon_key,notes:decryptText(row.notes_enc as string|null,key),status:row.status,changedAt:row.changed_at,reviewOn:row.review_on,createdAt:row.created_at,updatedAt:row.updated_at}));}
export function saveCredential(clientId:string,input:Record<string,unknown>,userId:string){const id=ensureScopedId("vault_credentials",typeof input.id==="string"?input.id:undefined,clientId),key=loadMasterKey(),now=new Date().toISOString(),url=safeServiceUrl(String(input.serviceUrl||"")),service=String(input.serviceName||"").trim().slice(0,120);if(!service)throw new Error("SERVICE_NAME_REQUIRED");run(`insert into vault_credentials(id,client_id,service_name,service_url,icon_key,login_enc,password_enc,notes_enc,status,changed_at,review_on,created_by,updated_by,created_at,updated_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(id) do update set service_name=excluded.service_name,service_url=excluded.service_url,icon_key=excluded.icon_key,login_enc=coalesce(excluded.login_enc,vault_credentials.login_enc),password_enc=coalesce(excluded.password_enc,vault_credentials.password_enc),notes_enc=excluded.notes_enc,status=excluded.status,changed_at=excluded.changed_at,review_on=excluded.review_on,updated_by=excluded.updated_by,updated_at=excluded.updated_at`,id,clientId,service,url,inputText(input,"iconKey",40),encryptText(inputText(input,"login",254),key),encryptText(inputText(input,"password",500),key),encryptText(inputText(input,"notes",2000),key),String(input.status||"active"),now,isoDate(inputText(input,"reviewOn",10)),userId,userId,now,now);audit({userId,action:"credential_saved",clientId,objectType:"credential",objectId:id,result:"success"});return {id};}
export function revealCredential(clientId:string,credentialId:string,field:"login"|"password",userId:string,address:string,purpose:"reveal"|"copy"="reveal"){const row=one<{login_enc:string|null;password_enc:string|null}>("select login_enc,password_enc from vault_credentials where id=? and client_id=? and deleted_at is null",credentialId,clientId);if(!row)throw new Error("NOT_FOUND");const value=decryptText(field==="login"?row.login_enc:row.password_enc,loadMasterKey());audit({userId,action:`${purpose}_${field}`,clientId,objectType:"credential",objectId:credentialId,result:"success",localAddress:address});return {value};}
export function listDocuments(clientId:string){const key=loadMasterKey();return all<Record<string,unknown>>("select id,title_enc,original_name_enc,document_type,document_on,expires_on,country_code,size_bytes,mime_type,created_at from vault_documents where client_id=? and deleted_at is null order by created_at desc",clientId).map(row=>({id:row.id,title:decryptText(row.title_enc as string,key),originalName:decryptText(row.original_name_enc as string,key),documentType:row.document_type,documentOn:row.document_on,expiresOn:row.expires_on,countryCode:row.country_code,sizeBytes:row.size_bytes,mimeType:row.mime_type,createdAt:row.created_at}));}

export function listCards(clientId:string){const key=loadMasterKey();return all<Record<string,unknown>>("select * from vault_cards where client_id=? and deleted_at is null order by created_at",clientId).map(row=>({id:row.id,bank:decryptText(row.bank_enc as string,key),brand:row.brand,cardName:decryptText(row.card_name_enc as string,key),lastFour:row.last_four,earningRate:row.earning_rate,earningCurrency:row.earning_currency,destinationProgram:row.destination_program,closingDay:row.closing_day,dueDay:row.due_day,notes:decryptText(row.notes_enc as string|null,key),createdAt:row.created_at,updatedAt:row.updated_at}));}
export function saveCard(clientId:string,input:Record<string,unknown>,userId:string){for(const forbidden of["number","cardNumber","cvv","password","bankPassword","token"])if(input[forbidden])throw new Error("FORBIDDEN_CARD_SECRET");const id=ensureScopedId("vault_cards",typeof input.id==="string"?input.id:undefined,clientId),lastFour=String(input.lastFour||"").trim(),closing=numberDay(input.closingDay),due=numberDay(input.dueDay);if(!/^\d{4}$/.test(lastFour))throw new Error("INVALID_LAST_FOUR");assertDay(closing);assertDay(due);const currency=input.earningCurrency==="BRL"?"BRL":"USD",key=loadMasterKey(),now=new Date().toISOString(),bank=inputText(input,"bank",100),cardName=inputText(input,"cardName",120);if(!bank||!cardName)throw new Error("CARD_FIELDS_REQUIRED");run(`insert into vault_cards(id,client_id,bank_enc,brand,card_name_enc,last_four,earning_rate,earning_currency,destination_program,closing_day,due_day,notes_enc,created_by,updated_by,created_at,updated_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(id) do update set bank_enc=excluded.bank_enc,brand=excluded.brand,card_name_enc=excluded.card_name_enc,last_four=excluded.last_four,earning_rate=excluded.earning_rate,earning_currency=excluded.earning_currency,destination_program=excluded.destination_program,closing_day=excluded.closing_day,due_day=excluded.due_day,notes_enc=excluded.notes_enc,updated_by=excluded.updated_by,updated_at=excluded.updated_at`,id,clientId,encryptText(bank,key)!,String(input.brand||"").slice(0,40),encryptText(cardName,key)!,lastFour,inputText(input,"earningRate",20),currency,inputText(input,"destinationProgram",100),closing,due,encryptText(inputText(input,"notes",1500),key),userId,userId,now,now);audit({userId,action:"card_admin_data_saved",clientId,objectType:"card",objectId:id,result:"success",metadata:{storesOnlyLastFour:true}});return {id};}

export function listPassports(clientId:string){const key=loadMasterKey();return all<Record<string,unknown>>("select * from vault_passports where client_id=? and deleted_at is null order by expires_on",clientId).map(row=>({id:row.id,number:decryptText(row.number_enc as string,key),issuerCountry:row.issuer_country,issuedOn:row.issued_on,expiresOn:row.expires_on,nationality:row.nationality,documentId:row.document_id,notes:decryptText(row.notes_enc as string|null,key),createdAt:row.created_at,updatedAt:row.updated_at}));}
export function savePassport(clientId:string,input:Record<string,unknown>,userId:string){const id=ensureScopedId("vault_passports",typeof input.id==="string"?input.id:undefined,clientId),number=inputText(input,"number",40);if(!number)throw new Error("PASSPORT_NUMBER_REQUIRED");const key=loadMasterKey(),now=new Date().toISOString(),documentId=inputText(input,"documentId",36);if(documentId&&!one("select id from vault_documents where id=? and client_id=? and deleted_at is null",documentId,clientId))throw new Error("DOCUMENT_NOT_FOUND");run(`insert into vault_passports(id,client_id,number_enc,issuer_country,issued_on,expires_on,nationality,document_id,notes_enc,created_by,updated_by,created_at,updated_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(id) do update set number_enc=excluded.number_enc,issuer_country=excluded.issuer_country,issued_on=excluded.issued_on,expires_on=excluded.expires_on,nationality=excluded.nationality,document_id=excluded.document_id,notes_enc=excluded.notes_enc,updated_by=excluded.updated_by,updated_at=excluded.updated_at`,id,clientId,encryptText(number,key)!,inputText(input,"issuerCountry",3),isoDate(inputText(input,"issuedOn",10)),isoDate(inputText(input,"expiresOn",10)),inputText(input,"nationality",80),documentId,encryptText(inputText(input,"notes",1500),key),userId,userId,now,now);audit({userId,action:"passport_saved",clientId,objectType:"passport",objectId:id,result:"success"});return {id};}
export function listVisas(clientId:string){const key=loadMasterKey();return all<Record<string,unknown>>("select * from vault_visas where client_id=? and deleted_at is null order by expires_on",clientId).map(row=>({id:row.id,visaType:row.visa_type,country:row.country,issuedOn:row.issued_on,expiresOn:row.expires_on,passportId:row.passport_id,documentId:row.document_id,notes:decryptText(row.notes_enc as string|null,key),createdAt:row.created_at,updatedAt:row.updated_at}));}
export function saveVisa(clientId:string,input:Record<string,unknown>,userId:string){const id=ensureScopedId("vault_visas",typeof input.id==="string"?input.id:undefined,clientId),country=inputText(input,"country",80);if(!country)throw new Error("VISA_COUNTRY_REQUIRED");const key=loadMasterKey(),now=new Date().toISOString(),passportId=inputText(input,"passportId",36),documentId=inputText(input,"documentId",36);if(passportId&&!one("select id from vault_passports where id=? and client_id=? and deleted_at is null",passportId,clientId))throw new Error("PASSPORT_NOT_FOUND");if(documentId&&!one("select id from vault_documents where id=? and client_id=? and deleted_at is null",documentId,clientId))throw new Error("DOCUMENT_NOT_FOUND");run(`insert into vault_visas(id,client_id,visa_type,country,issued_on,expires_on,passport_id,document_id,notes_enc,created_by,updated_by,created_at,updated_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(id) do update set visa_type=excluded.visa_type,country=excluded.country,issued_on=excluded.issued_on,expires_on=excluded.expires_on,passport_id=excluded.passport_id,document_id=excluded.document_id,notes_enc=excluded.notes_enc,updated_by=excluded.updated_by,updated_at=excluded.updated_at`,id,clientId,inputText(input,"visaType",80),country,isoDate(inputText(input,"issuedOn",10)),isoDate(inputText(input,"expiresOn",10)),passportId,documentId,encryptText(inputText(input,"notes",1500),key),userId,userId,now,now);audit({userId,action:"visa_saved",clientId,objectType:"visa",objectId:id,result:"success"});return {id};}
