let csrf="";
async function request<T>(path:string,options:RequestInit={}){const response=await fetch(`/api${path}`,{...options,credentials:"include",headers:{...(options.body instanceof ArrayBuffer?{}:{"Content-Type":"application/json"}),...(csrf?{"X-Vault-CSRF":csrf}:{}),...options.headers}});const type=response.headers.get("content-type")||"";const data=type.includes("application/json")?await response.json():await response.arrayBuffer();if(!response.ok)throw new Error((data as {error?:string}).error||"Falha no cofre local");return data as T;}
export async function login(username:string,password:string,totp:string){const result=await request<{csrf:string;user:{role:string}}>("/auth/login",{method:"POST",body:JSON.stringify({username,password,totp})});csrf=result.csrf;return result;}
export async function session(){const result=await request<{user:{id:string;username:string;role:string};csrf:string}>("/auth/session");csrf=result.csrf;return result;}
export const logout=()=>request("/auth/logout",{method:"POST",body:"{}"});
export const getAudit=()=>request<{items:Array<Record<string,unknown>>}>("/audit");
export const getClient=(id:string)=>request<VaultClient>(`/clients/${id}`);
export const savePersonal=(id:string,value:Record<string,unknown>)=>request<VaultClient>(`/clients/${id}`,{method:"PUT",body:JSON.stringify(value)});
export const saveCredential=(clientId:string,value:Record<string,unknown>)=>request(`/clients/${clientId}/credentials`,{method:"POST",body:JSON.stringify(value)});
export const reveal=(clientId:string,id:string,field:"login"|"password")=>request<{value:string|null}>(`/clients/${clientId}/credentials/${id}/${field}`,{method:"POST",body:"{}"});
export const removeDocument=(clientId:string,id:string)=>request(`/clients/${clientId}/documents/${id}`,{method:"DELETE",body:"{}"});
export async function uploadDocument(clientId:string,file:File,meta:Record<string,unknown>){const encoded=btoa(unescape(encodeURIComponent(JSON.stringify({...meta,originalName:file.name,mimeType:file.type})))).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");return request(`/clients/${clientId}/documents`,{method:"POST",body:await file.arrayBuffer(),headers:{"Content-Type":"application/octet-stream","X-Vault-Metadata":encoded}});}
export interface VaultClient{clientId:string;displayName:string;status:string;contractStartDate:string|null;contractEndDate:string|null;syncStatus:string;createdAt:string;updatedAt:string;lastAdminUserId:string|null;personal:{cpf:string|null;rg:string|null;birthDate:string|null;nextBirthday:string|null;email:string|null;phone:string|null;address:string|null;privateNotes:string|null};credentials:Array<{id:string;serviceName:string;serviceUrl:string;iconKey:string|null;status:string;changedAt:string;reviewOn:string|null}>;documents:Array<{id:string;title:string|null;originalName:string|null;documentType:string;expiresOn:string|null;sizeBytes:number;mimeType:string;createdAt:string}>}
