import { keepPreviousData, useQuery } from "@tanstack/react-query";
import { Search, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { EmptyState, ErrorState, LoadingState, PageHeader } from "@/components/admin/AdminPage";
import { AppShell } from "@/components/layout/AppShell";
import { formatDate, formatPoints } from "@/lib/formatters";
import { getPointsRanking } from "@/services/points";

export function AdminPointsPage() { const [input,setInput]=useState(""); const [search,setSearch]=useState(""); const [offset,setOffset]=useState(0); useEffect(()=>{const id=setTimeout(()=>{setSearch(input.trim());setOffset(0);},300);return()=>clearTimeout(id);},[input]); const query=useQuery({queryKey:["points-ranking",search,offset],queryFn:()=>getPointsRanking(search,20,offset),placeholderData:keepPreviousData}); return <AppShell title="Pontuações" hideHeading><PageHeader eyebrow="Inteligência de carteira" title="Pontuações" description="Ranking calculado no servidor sobre o último saldo oficial de cada programa." action={<div className="search-field"><Search size={17}/><input aria-label="Pesquisar no ranking" value={input} onChange={(e)=>setInput(e.target.value)} placeholder="Pesquisar cliente"/></div>}/>{query.isLoading&&<LoadingState/>}{query.isError&&<ErrorState message={query.error.message} retry={()=>void query.refetch()}/>} {query.data?.items.length===0&&<EmptyState title="Ranking vazio" description="Cadastre saldos para formar o ranking."/>}{query.data&&query.data.items.length>0&&<><div className="ranking-list">{query.data.items.map((item)=><article key={item.clientId} className="ranking-row"><div className="ranking-position">{item.position<=3?<Trophy aria-hidden/>:null}<strong>{item.position}º</strong></div><div className="ranking-client"><h2>{item.clientName}</h2><p>{item.programs.map((p)=>`${p.programName} ${formatPoints(p.balance)}`).join(" · ")||"Sem contas"}</p></div><div><span>Saldo total</span><strong>{formatPoints(item.totalPoints)}</strong></div><div><span>Vence 30 / 60 / 90</span><strong>{formatPoints(item.expiring30)} / {formatPoints(item.expiring60)} / {formatPoints(item.expiring90)}</strong></div><div><span>Último movimento</span><strong>{formatDate(item.lastMovementAt)}</strong></div></article>)}</div><Pagination offset={offset} total={query.data.total} pending={query.isFetching} setOffset={setOffset}/></>}</AppShell>; }
function Pagination({offset,total,pending,setOffset}:{offset:number;total:number;pending:boolean;setOffset:(n:number)=>void}){return <div className="pagination-bar"><span>{offset+1}–{Math.min(offset+20,total)} de {total}</span><div><button className="secondary-button" disabled={!offset||pending} onClick={()=>setOffset(Math.max(0,offset-20))}>Anterior</button><button className="secondary-button" disabled={offset+20>=total||pending} onClick={()=>setOffset(offset+20)}>Próxima</button></div></div>}
