import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowDownAZ, CalendarClock, CalendarRange, Coins, PiggyBank, Search, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { ProtectedDataButton } from "@/components/admin/ProtectedDataButton";
import { StatusBadge } from "@/components/admin/AdminFields";
import { EmptyState, ErrorState, LoadingState, PageHeader } from "@/components/admin/AdminPage";
import { AppShell } from "@/components/layout/AppShell";
import { formatCurrency, formatDate } from "@/lib/formatters";
import { getManagementTerms } from "@/services/management-terms";
import type { ManagementTermItem } from "@/types/management-terms";

const optionalNumber = (value: string) => { const parsed = Number(value.replace(/\./g, "").replace(",", ".")); return value.trim() && Number.isFinite(parsed) ? parsed : null; };
const termLabel: Record<string, string> = { active: "Ativa", expiring: "Vence em até 30 dias", ended: "Encerrada", no_term: "Sem vigência", archived: "Arquivada" };

export function AdminManagementTermsPage() {
  const [filters, setFilters] = useState({ search: "", termStatus: "all", clientStatus: "all", startFrom: "", startTo: "", endFrom: "", endTo: "", hasSavings: "all", hasCashback: "all", savingsMin: "", savingsMax: "", cashbackMin: "", cashbackMax: "", sortBy: "client_name", sortDirection: "asc" as "asc" | "desc", offset: 0 });
  const terms = useQuery({ queryKey: ["management-terms", filters], queryFn: () => getManagementTerms({ ...filters, hasSavings: filters.hasSavings === "all" ? null : filters.hasSavings === "yes", hasCashback: filters.hasCashback === "all" ? null : filters.hasCashback === "yes", savingsMin: optionalNumber(filters.savingsMin), savingsMax: optionalNumber(filters.savingsMax), cashbackMin: optionalNumber(filters.cashbackMin), cashbackMax: optionalNumber(filters.cashbackMax), limit: 25 }) });
  const set = (name: keyof typeof filters, value: string | number) => setFilters((current) => ({ ...current, [name]: value, offset: name === "offset" ? Number(value) : 0 }));
  const data = terms.data;
  return <AppShell title="Vigências" hideHeading>
    <PageHeader eyebrow="Gestão contratual" title="Vigências dos clientes" description="Prazos, economia e cashback calculados sobre a vigência canônica, sem consultar nenhum dado do cofre local." />
    {data && <section className="term-summary-strip" aria-label="Indicadores de vigências"><Summary icon={<CalendarRange />} label="Ativas" value={String(data.summary.active)} /><Summary icon={<CalendarClock />} label="Vencem em 30 dias" value={String(data.summary.expiring)} warning /><Summary icon={<CalendarClock />} label="Encerradas" value={String(data.summary.ended)} /><Summary icon={<CalendarRange />} label="Sem vigência" value={String(data.summary.noTerm)} /><Summary icon={<PiggyBank />} label="Economia na vigência" value={formatCurrency(data.summary.totalSavings)} highlight /><Summary icon={<Coins />} label="Cashback na vigência" value={formatCurrency(data.summary.totalCashback)} highlight /></section>}
    <section className="management-term-filters module-form"><div className="form-title"><Search /><div><h2>Filtros e ordenação</h2><p>Combine situação, datas e intervalos financeiros.</p></div></div><div className="term-filter-grid">
      <label className="term-search">Cliente<input value={filters.search} onChange={(e) => set("search", e.target.value)} placeholder="Buscar pelo nome" /></label>
      <label>Situação<select value={filters.termStatus} onChange={(e) => set("termStatus", e.target.value)}><option value="all">Todas</option><option value="active">Ativa</option><option value="expiring">Vence em 30 dias</option><option value="ended">Encerrada</option><option value="no_term">Sem vigência</option><option value="archived">Arquivada</option></select></label>
      <label>Cliente<select value={filters.clientStatus} onChange={(e) => set("clientStatus", e.target.value)}><option value="all">Ativos e arquivados</option><option value="active">Ativos</option><option value="archived">Arquivados</option></select></label>
      <label>Início mínimo<input type="date" value={filters.startFrom} onChange={(e) => set("startFrom", e.target.value)} /></label><label>Início máximo<input type="date" value={filters.startTo} onChange={(e) => set("startTo", e.target.value)} /></label><label>Final mínimo<input type="date" value={filters.endFrom} onChange={(e) => set("endFrom", e.target.value)} /></label><label>Final máximo<input type="date" value={filters.endTo} onChange={(e) => set("endTo", e.target.value)} /></label>
      <label>Economia<select value={filters.hasSavings} onChange={(e) => set("hasSavings", e.target.value)}><option value="all">Com ou sem economia</option><option value="yes">Com economia</option><option value="no">Sem economia</option></select></label><label>Cashback<select value={filters.hasCashback} onChange={(e) => set("hasCashback", e.target.value)}><option value="all">Com ou sem cashback</option><option value="yes">Com cashback</option><option value="no">Sem cashback</option></select></label>
      <label>Economia mínima<input inputMode="decimal" value={filters.savingsMin} onChange={(e) => set("savingsMin", e.target.value)} /></label><label>Economia máxima<input inputMode="decimal" value={filters.savingsMax} onChange={(e) => set("savingsMax", e.target.value)} /></label><label>Cashback mínimo<input inputMode="decimal" value={filters.cashbackMin} onChange={(e) => set("cashbackMin", e.target.value)} /></label><label>Cashback máximo<input inputMode="decimal" value={filters.cashbackMax} onChange={(e) => set("cashbackMax", e.target.value)} /></label>
      <label>Ordenar por<select value={filters.sortBy} onChange={(e) => set("sortBy", e.target.value)}><option value="client_name">Nome do cliente</option><option value="starts_on">Início</option><option value="ends_on">Final</option><option value="remaining_days">Dias restantes</option><option value="total_days">Tempo total</option><option value="savings">Economia</option><option value="cashback">Cashback</option><option value="last_activity">Último lançamento</option></select></label><button className="secondary-button term-sort-direction" onClick={() => set("sortDirection", filters.sortDirection === "asc" ? "desc" : "asc")}><ArrowDownAZ /> {filters.sortDirection === "asc" ? "Crescente" : "Decrescente"}</button>
    </div></section>
    <section className="data-section management-terms-section"><div className="section-heading"><div><span className="eyebrow">Carteira contratual</span><h2>Clientes e vigências</h2><p>{data ? `${data.total} cliente(s) no recorte atual` : "Dados oficiais"}</p></div></div>
      {terms.isLoading && <LoadingState />}{terms.isError && <ErrorState message={terms.error.message} retry={() => void terms.refetch()} />}{data && data.items.length === 0 && <EmptyState title="Nenhuma vigência encontrada" description="Ajuste os filtros ou cadastre a vigência no perfil do cliente." />}
      {data && data.items.length > 0 && <><div className="responsive-table management-terms-table"><table><thead><tr><th>Cliente</th><th>Situação</th><th>Período</th><th>Tempo</th><th>Progresso</th><th>Economia</th><th>Cashback</th><th>Último lançamento</th><th>Ações</th></tr></thead><tbody>{data.items.map((item) => <TermRow key={item.clientId} item={item} canVault={data.canVaultAccess} />)}</tbody></table></div><div className="management-term-cards">{data.items.map((item) => <TermCard key={item.clientId} item={item} canVault={data.canVaultAccess} />)}</div><div className="pagination-bar"><span>{filters.offset + 1}–{Math.min(filters.offset + 25, data.total)} de {data.total}</span><div><button className="secondary-button" disabled={!filters.offset || terms.isFetching} onClick={() => set("offset", Math.max(0, filters.offset - 25))}>Anterior</button><button className="secondary-button" disabled={filters.offset + 25 >= data.total || terms.isFetching} onClick={() => set("offset", filters.offset + 25)}>Próxima</button></div></div></>}
    </section>
  </AppShell>;
}

function Summary({ icon, label, value, warning, highlight }: { icon: React.ReactNode; label: string; value: string; warning?: boolean; highlight?: boolean }) { return <article className={`${warning ? "warning" : ""} ${highlight ? "highlight" : ""}`}>{icon}<span>{label}</span><strong>{value}</strong></article>; }
function Progress({ item }: { item: ManagementTermItem }) { return <div className="term-progress"><div><i style={{ width: `${item.progressPercent}%` }} /></div><span>{item.progressPercent}%</span></div>; }
function Actions({ item, canVault }: { item: ManagementTermItem; canVault: boolean }) { return <div className="term-actions"><Link className="table-action" to={`/admin/clientes/${item.clientId}`}>Abrir perfil</Link><Link className="table-action" to={`/admin/clientes/${item.clientId}/editar#contrato`}>Editar vigência</Link><ProtectedDataButton clientId={item.clientId} allowed={canVault} compact state={item.vaultSyncStatus??(item.termStatus==="no_term"?"pending":"synced")} /></div>; }
function TermRow({ item, canVault }: { item: ManagementTermItem; canVault: boolean }) { return <tr><td><strong>{item.clientName}</strong><small>{item.clientStatus === "ended" ? "Arquivado" : "Ativo"}</small></td><td><StatusBadge status={item.termStatus} /><small>{termLabel[item.termStatus]}</small></td><td><strong>{item.startsOn ? formatDate(item.startsOn) : "—"}</strong><small>até {item.endsOn ? formatDate(item.endsOn) : "prazo aberto"}</small></td><td><strong>{item.totalDays == null ? "—" : `${item.totalDays} dias`}</strong><small>{item.remainingDays == null ? "Sem data final" : item.remainingDays < 0 ? `${Math.abs(item.remainingDays)} dias encerrada` : `${item.remainingDays} dias restantes`}</small></td><td><Progress item={item} /></td><td><strong>{formatCurrency(item.savings)}</strong><small>Hist. {formatCurrency(item.historicalSavings)}</small></td><td><strong>{formatCurrency(item.cashback)}</strong><small>Hist. {formatCurrency(item.historicalCashback)}</small></td><td>{item.lastActivity ? formatDate(item.lastActivity) : "—"}</td><td><Actions item={item} canVault={canVault} /></td></tr>; }
function TermCard({ item, canVault }: { item: ManagementTermItem; canVault: boolean }) { return <article><header><div><span>{item.clientStatus === "ended" ? "Cliente arquivado" : "Cliente ativo"}</span><h3>{item.clientName}</h3></div><StatusBadge status={item.termStatus} /></header><div className="term-card-period"><CalendarRange /><span>{item.startsOn ? formatDate(item.startsOn) : "Sem início"}<small>{item.endsOn ? `até ${formatDate(item.endsOn)}` : "prazo aberto"}</small></span><strong>{item.remainingDays == null ? "—" : `${item.remainingDays} dias`}</strong></div><Progress item={item} /><div className="term-card-values"><span>Economia<strong>{formatCurrency(item.savings)}</strong></span><span>Cashback<strong>{formatCurrency(item.cashback)}</strong></span><span>Último lançamento<strong>{item.lastActivity ? formatDate(item.lastActivity) : "—"}</strong></span></div><Actions item={item} canVault={canVault} /></article>; }
