import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CreditCard, ReceiptText } from "lucide-react";
import { ClientSelect, StatusBadge } from "@/components/admin/AdminFields";
import { EmptyState, ErrorState, LoadingState, PageHeader } from "@/components/admin/AdminPage";
import { AppShell } from "@/components/layout/AppShell";
import { parseMoneyPtBr } from "@/lib/admin-inputs";
import { formatCurrency, formatDate, formatPoints } from "@/lib/formatters";
import { getAdminFormOptions } from "@/services/admin-options";
import { getCardStatementOptions, getCardStatements, recordCardStatement, upsertCreditCard } from "@/services/invoices";

const currentMonth = new Date().toISOString().slice(0, 7);

export function AdminInvoicesPage() {
  const queryClient = useQueryClient();
  const adminOptions = useQuery({ queryKey: ["admin-form-options"], queryFn: getAdminFormOptions });
  const options = useQuery({ queryKey: ["card-options"], queryFn: getCardStatementOptions });
  const [filterClient, setFilterClient] = useState("");
  const [filterStatus, setFilterStatus] = useState("all");
  const statements = useQuery({ queryKey: ["card-statements", filterClient, filterStatus], queryFn: () => getCardStatements({ clientId: filterClient, status: filterStatus }) });
  const [card, setCard] = useState({ clientId: "", issuer: "", productName: "", brand: "", lastFour: "", programId: "", basis: "brl" as "brl" | "usd", pointsPerUnit: "1", ruleDescription: "" });
  const [statement, setStatement] = useState({ cardId: "", statementMonth: currentMonth, totalSpend: "", eligibleSpend: "", receivedPoints: "0", fxRate: "", fxRateDate: "", fxSource: "", notes: "" });
  const cardMutation = useMutation({ mutationFn: () => upsertCreditCard({ ...card, pointsPerUnit: Number(card.pointsPerUnit.replace(",", ".")) }), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["card-options"] }) });
  const statementMutation = useMutation({ mutationFn: () => recordCardStatement({ cardId: statement.cardId, statementMonth: statement.statementMonth, totalSpend: parseMoneyPtBr(statement.totalSpend), eligibleSpend: parseMoneyPtBr(statement.eligibleSpend), receivedPoints: Number(statement.receivedPoints.replace(/\./g, "").replace(",", ".")) || 0, fxRate: statement.fxRate ? Number(statement.fxRate.replace(",", ".")) : null, fxRateDate: statement.fxRateDate, fxSource: statement.fxSource, notes: statement.notes, operationId: crypto.randomUUID() }), onSuccess: () => void Promise.all([queryClient.invalidateQueries({ queryKey: ["card-statements"] }), queryClient.invalidateQueries({ queryKey: ["card-options"] })]) });
  const selectedCard = useMemo(() => options.data?.cards.find((item) => item.cardId === statement.cardId), [options.data, statement.cardId]);

  return <AppShell title="Faturas" hideHeading>
    <PageHeader eyebrow="Cartões" title="Faturas e pontos esperados" description="Regras e cotações ficam congeladas no registro. Número completo de cartão nunca é armazenado." />
    {(adminOptions.isLoading || options.isLoading) && <LoadingState />}{(adminOptions.isError || options.isError) && <ErrorState message={(adminOptions.error ?? options.error)?.message ?? "Falha ao carregar faturas"} />}
    {adminOptions.data && options.data && <section className="module-grid two-columns">
      <form className="module-form" onSubmit={(event) => { event.preventDefault(); cardMutation.mutate(); }}>
        <div className="form-title"><CreditCard /><div><h2>Novo cartão/regra</h2><p>Cadastre apenas dados não sensíveis e a regra vigente.</p></div></div>
        <div className="form-grid"><label>Cliente<ClientSelect clients={adminOptions.data.clients} value={card.clientId} onChange={(clientId) => setCard((current) => ({ ...current, clientId }))} /></label><label>Emissor<input value={card.issuer} onChange={(event) => setCard((current) => ({ ...current, issuer: event.target.value }))} required /></label><label>Produto<input value={card.productName} onChange={(event) => setCard((current) => ({ ...current, productName: event.target.value }))} required /></label><label>Bandeira<input value={card.brand} onChange={(event) => setCard((current) => ({ ...current, brand: event.target.value }))} /></label><label>Últimos 4 dígitos<input value={card.lastFour} maxLength={4} onChange={(event) => setCard((current) => ({ ...current, lastFour: event.target.value.replace(/\D/g, "").slice(0, 4) }))} required /></label><label>Base<select value={card.basis} onChange={(event) => setCard((current) => ({ ...current, basis: event.target.value as "brl" | "usd" }))}><option value="brl">Por real</option><option value="usd">Por dólar</option></select></label><label>Pontos por unidade<input inputMode="decimal" value={card.pointsPerUnit} onChange={(event) => setCard((current) => ({ ...current, pointsPerUnit: event.target.value }))} /></label><label className="field-full">Descrição da regra<textarea value={card.ruleDescription} onChange={(event) => setCard((current) => ({ ...current, ruleDescription: event.target.value }))} /></label></div>
        {cardMutation.isError && <div className="form-error">{cardMutation.error.message}</div>}{cardMutation.isSuccess && <div className="form-success">Cartão e regra salvos.</div>}<button className="primary-button" disabled={cardMutation.isPending}>Salvar cartão</button>
      </form>
      <form className="module-form" onSubmit={(event) => { event.preventDefault(); statementMutation.mutate(); }}>
        <div className="form-title"><ReceiptText /><div><h2>Lançar fatura</h2><p>A estimativa visual é recalculada oficialmente pelo backend ao salvar.</p></div></div>
        <div className="form-grid"><label>Cartão<select value={statement.cardId} onChange={(event) => setStatement((current) => ({ ...current, cardId: event.target.value }))} required><option value="">Selecione</option>{options.data.cards.map((item) => <option key={item.cardId} value={item.cardId}>{item.label}</option>)}</select></label><label>Competência<input type="month" value={statement.statementMonth} onChange={(event) => setStatement((current) => ({ ...current, statementMonth: event.target.value }))} /></label><label>Total<input inputMode="decimal" value={statement.totalSpend} onChange={(event) => setStatement((current) => ({ ...current, totalSpend: event.target.value }))} /></label><label>Elegível<input inputMode="decimal" value={statement.eligibleSpend} onChange={(event) => setStatement((current) => ({ ...current, eligibleSpend: event.target.value }))} /></label><label>Recebidos<input inputMode="numeric" value={statement.receivedPoints} onChange={(event) => setStatement((current) => ({ ...current, receivedPoints: event.target.value }))} /></label>{selectedCard?.basis === "usd" && <><label>Cotação<input inputMode="decimal" value={statement.fxRate} onChange={(event) => setStatement((current) => ({ ...current, fxRate: event.target.value }))} /></label><label>Data cotação<input type="date" value={statement.fxRateDate} onChange={(event) => setStatement((current) => ({ ...current, fxRateDate: event.target.value }))} /></label><label>Origem cotação<input value={statement.fxSource} onChange={(event) => setStatement((current) => ({ ...current, fxSource: event.target.value }))} /></label></>}<label className="field-full">Observação<textarea value={statement.notes} onChange={(event) => setStatement((current) => ({ ...current, notes: event.target.value }))} /></label></div>
        {statementMutation.isError && <div className="form-error">{statementMutation.error.message}</div>}{statementMutation.isSuccess && <div className="form-success">Fatura registrada.</div>}<button className="primary-button" disabled={statementMutation.isPending}>Registrar fatura</button>
      </form>
    </section>}
    <section className="data-section"><div className="section-heading"><div><span className="eyebrow">Conciliação</span><h2>Faturas recentes</h2></div>{adminOptions.data && <div className="data-filters"><ClientSelect clients={adminOptions.data.clients} value={filterClient} onChange={setFilterClient} /><select value={filterStatus} onChange={(event) => setFilterStatus(event.target.value)}><option value="all">Todos</option><option value="calculated">Calculadas</option><option value="reconciled">Conciliadas</option><option value="divergent">Divergentes</option></select></div>}</div>
      {statements.isLoading && <LoadingState />}{statements.isError && <ErrorState message={statements.error.message} />}{statements.data?.items.length === 0 && <EmptyState title="Nenhuma fatura" description="Cadastre um cartão e registre a primeira competência." />}{statements.data && statements.data.items.length > 0 && <div className="responsive-table"><table><thead><tr><th>Cliente</th><th>Competência</th><th>Cartão</th><th>Elegível</th><th>Esperado</th><th>Recebido</th><th>Status</th></tr></thead><tbody>{statements.data.items.map((item) => <tr key={item.statementId}><td>{item.clientName}</td><td>{formatDate(item.statementMonth)}</td><td><strong>{item.cardLabel}</strong><small>{item.earningBasis === "usd" ? `USD ${item.fxRate ?? "-"}` : `${item.earningRate} pts/R$`}</small></td><td>{formatCurrency(item.eligibleSpend)}</td><td>{formatPoints(item.expectedPoints)}</td><td><span className={item.difference < 0 ? "value-negative" : "value-positive"}>{formatPoints(item.receivedPoints)}</span><small>Dif. {formatPoints(item.difference)}</small></td><td><StatusBadge status={item.status} /></td></tr>)}</tbody></table></div>}
    </section>
  </AppShell>;
}
