import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CircleMinus } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ClientSelect, ProgramAccountSelect } from "@/components/admin/AdminFields";
import { ErrorState, LoadingState, PageHeader } from "@/components/admin/AdminPage";
import { AppShell } from "@/components/layout/AppShell";
import { parsePointsPtBr } from "@/lib/admin-inputs";
import { formatPoints } from "@/lib/formatters";
import { getAdminFormOptions } from "@/services/admin-options";
import { recordManualExit } from "@/services/manual-exits";
const today=new Date().toISOString().slice(0,10);const schema=z.object({clientId:z.string().uuid(),accountId:z.string().uuid(),exitDate:z.string().min(1).refine(v=>v<=today,"A data não pode estar no futuro"),points:z.string().refine(v=>{try{return parsePointsPtBr(v)>0}catch{return false}},"Informe pontos válidos"),notes:z.string().trim().min(3,"A observação é obrigatória")});type FormData=z.infer<typeof schema>;
export function AdminManualExitsPage(){const qc=useQueryClient();const options=useQuery({queryKey:["admin-form-options"],queryFn:getAdminFormOptions});const [operationId,setOperationId]=useState(()=>crypto.randomUUID());const form=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{clientId:"",accountId:"",exitDate:today,points:"",notes:""}});const client=options.data?.clients.find(c=>c.clientId===form.watch("clientId"));const account=client?.accounts.find(a=>a.accountId===form.watch("accountId"));const mutation=useMutation({mutationFn:recordManualExit,onSuccess:()=>{setOperationId(crypto.randomUUID());form.reset({...form.getValues(),points:"",notes:""});void Promise.all([qc.invalidateQueries({queryKey:["admin-form-options"]}),qc.invalidateQueries({queryKey:["admin-overview"]}),qc.invalidateQueries({queryKey:["points-ranking"]})])}});return <AppShell title="Saída Manual" hideHeading><PageHeader eyebrow="Ajuste excepcional" title="Saída Manual" description="Baixa imutável com justificativa, idempotência e preservação do custo médio."/>{options.isLoading&&<LoadingState/>}{options.isError&&<ErrorState message={options.error.message}/>} {options.data&&<form className="module-form compact-operation" onSubmit={form.handleSubmit(v=>mutation.mutate({clientId:v.clientId,accountId:v.accountId,exitDate:v.exitDate,points:parsePointsPtBr(v.points),notes:v.notes,operationId}))}><div className="form-title"><CircleMinus/><div><h2>Registrar saída</h2><p>Use apenas quando a baixa não pertence a uma transferência ou viagem já registrada.</p></div></div><div className="form-grid"><label>Cliente<ClientSelect clients={options.data.clients} value={form.watch("clientId")} onChange={v=>{form.setValue("clientId",v,{shouldValidate:true});form.setValue("accountId","")}}/></label><label>Programa<ProgramAccountSelect client={client} value={form.watch("accountId")} onChange={v=>form.setValue("accountId",v,{shouldValidate:true})}/></label><label>Saldo atual<input readOnly value={account?`${formatPoints(account.balance)} pontos`:"Selecione a conta"}/></label><label>Data da saída<input type="date" max={today}{...form.register("exitDate")}/></label><label>Quantidade<input inputMode="numeric" placeholder="10.000" {...form.register("points")}/></label><label className="field-full">Observação obrigatória<textarea {...form.register("notes")}/>{form.formState.errors.notes&&<small className="field-error">{form.formState.errors.notes.message}</small>}</label></div>{mutation.isError&&<div className="form-error">{mutation.error.message}</div>}{mutation.isSuccess&&<div className="form-success">Saída registrada. Novo saldo: {formatPoints(Number((mutation.data as {newBalance:number}).newBalance))} pontos.</div>}<button className="primary-button" disabled={!options.data.canWrite||mutation.isPending}>{mutation.isPending?"Registrando...":"Confirmar saída manual"}</button></form>}</AppShell>}
